# Generated by Django 5.0.3 on 2024-04-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_customuser_address_remove_customuser_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
