# Generated by Django 5.0.3 on 2024-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_customuser_address_customuser_hobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProFile',
        ),
    ]
