# Generated by Django 5.0.3 on 2024-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_guestbookentry_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='guest_password',
            field=models.CharField(default='admin', max_length=15),
        ),
    ]
