# Generated by Django 5.0.3 on 2024-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_guestbookentry_guest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/profile_pics/'),
        ),
    ]
