# Generated by Django 5.0.3 on 2024-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
