# Generated by Django 5.0.3 on 2024-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
