# Generated by Django 5.0.3 on 2024-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
