# Generated by Django 5.0.3 on 2024-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_alter_customuser_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
