# Generated by Django 5.0.3 on 2024-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0020_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
